name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  collect-data:
    runs-on: ubuntu-latest

    steps:
    - name: Report rust version
      run: |
        rustc -vV
        rustup update
        rustc -vV

    - uses: actions/checkout@v5

    - name: Download binary
      uses: actions/download-artifact@v6
      with:
        name: pydigger-linux-release
        path: pydigger
        repository: szabgab/pydigger.rs

    - name: List
      run: |
        ls -al
        tree

    - name: Collect data
      run: ./pydigger --download --report

    - name: Tree
      run: tree

#    - name: Commit new data
#      run: |
#        cd data
#        GIT_STATUS=$(git status --porcelain)
#        echo $GIT_STATUS
#        git config user.name github-actions[bot]
#        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#        git add .
#        if [ "$GIT_STATUS" != "" ]; then git commit -m "Automated data collection"; fi
#        if [ "$GIT_STATUS" != "" ]; then git push; fi
